// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/api/v1/off.ts";
import * as $3 from "./routes/api/v1/on.ts";
import * as $4 from "./routes/api/v1/set.ts";
import * as $5 from "./routes/api/v1/set/[color].ts";
import * as $6 from "./routes/api/v1/status.ts";
import * as $7 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/api/v1/off.ts": $2,
    "./routes/api/v1/on.ts": $3,
    "./routes/api/v1/set.ts": $4,
    "./routes/api/v1/set/[color].ts": $5,
    "./routes/api/v1/status.ts": $6,
    "./routes/index.tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
